{
    "openapi": "3.0.0",
    "info": {
        "title": "E-commerce System",
        "description": "Sistema básico de cadastro de usuários, produtos e vendas.",
        "version": "1.0.0"
    },
    "paths": {
        "/users": {
            "post": {
                "summary": "Cadastra um novo usuário",
                "tags": ["USUÁRIOS"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuário"
                            },
                            "examples": {
                                "Register": {
                                    "summary": "Cadastra um novo usuário",
                                    "value": {
                                        "name": "João da Silva",
                                        "email": "joao.silva@email.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Usuário cadastrado com sucesso!"
                    },
                    "409": {
                        "description": "É retornado quando já existe um usuário cadastrado no sistema com o email informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 409,
                                            "message": "User with email 'joaozinho@email.com' already exists",
                                            "error": "Conflict"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Retorna todos os produtos cadastrados",
                "tags": ["USUÁRIOS"],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Search": {
                                        "value": [
                                            {
                                                "id": "38c9c1a2-7c82-4eed-9880-4609bfb0ed41",
                                                "name": "João da Silva",
                                                "email": "joao.silva@email.com",
                                                "password": "123456"
                                            },
                                            {
                                                "id": "bfe45fc3-bea7-45e8-9a3a-575198faedf4",
                                                "name": "Maria Aparecida",
                                                "email": "maria.aparecida@email.com",
                                                "password": "654321"
                                            },
                                            {
                                                "id": "1e440c4b-9817-4c10-bb57-ce7c5310d095",
                                                "name": "José de Paula",
                                                "email": "jose.paula@email.com",
                                                "password": "senha123"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "summary": "Retorna um usuário específico de acordo com o ID informado",
                "tags": ["USUÁRIOS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Search": {
                                        "summary": "Retorna um usuário específico",
                                        "value": {
                                            "id": "38c9c1a2-7c82-4eed-9880-4609bfb0ed41",
                                            "name": "João da Silva",
                                            "email": "joao.silva@email.com",
                                            "password": "123456"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado com o id informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Altera a senha do usuário",
                "tags": ["USUÁRIOS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserUpdate"
                            },
                            "examples": {
                                "Update": {
                                    "summary": "Altera a senha do usuário",
                                    "value": {
                                        "password": "123456@"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Senha alterada com sucesso!"
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado com o id informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta um produto de acordo com o ID informado",
                "tags": ["USUÁRIOS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário deletado com sucesso!"
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/products": {
            "post": {
                "summary": "Cadastra um novo produto",
                "tags": ["PRODUCTS"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Produto"
                            },
                            "examples": {
                                "Register": {
                                    "summary": "Cadastra um novo produto",
                                    "value": {
                                        "name": "Notebook Dell Inspiron 5406",
                                        "price": 4615.99,
                                        "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ23456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Produto cadastrado com sucesso!"
                    },
                    "409": {
                        "description": "É retornado quando já existe um produto cadastrado no sistema com o nome informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 409,
                                            "message": "product with name 'Notebook Dell Inspiron 5406' already exists",
                                            "error": "Conflict"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Retorna todos os produtos cadastrados",
                "tags": ["PRODUCTS"],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Search": {
                                        "value": [
                                            {
                                                "id": "38c9c1a2-7c82-4eed-9880-4609bfb0ed41",
                                                "name": "João da Silva",
                                                "email": "joao.silva@email.com",
                                                "password": "123456"
                                            },
                                            {
                                                "id": "bfe45fc3-bea7-45e8-9a3a-575198faedf4",
                                                "name": "Maria Aparecida",
                                                "email": "maria.aparecida@email.com",
                                                "password": "654321"
                                            },
                                            {
                                                "id": "1e440c4b-9817-4c10-bb57-ce7c5310d095",
                                                "name": "José de Paula",
                                                "email": "jose.paula@email.com",
                                                "password": "senha123"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "summary": "Retorna um usuário específico de acordo com o ID informado",
                "tags": ["PRODUCTS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Search": {
                                        "summary": "Retorna um usuário específico",
                                        "value": {
                                            "id": "38c9c1a2-7c82-4eed-9880-4609bfb0ed41",
                                            "name": "João da Silva",
                                            "email": "joao.silva@email.com",
                                            "password": "123456"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado com o id informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Altera a senha do usuário",
                "tags": ["PRODUCTS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserUpdate"
                            },
                            "examples": {
                                "Update": {
                                    "summary": "Altera a senha do usuário",
                                    "value": {
                                        "password": "123456@"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Senha alterada com sucesso!"
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado com o id informado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta um produto de acordo com o ID informado",
                "tags": ["PRODUCTS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário deletado com sucesso!"
                    },
                    "404": {
                        "description": "É retornado quando um usuário não é encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "user with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "É retornado quando ocorreu algum erro no servidor",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 500,
                                            "message": "Internal server error",
                                            "error": "Internal Server Error"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "summary": "Cadastra um novo pedido",
                "tags": ["COMPRAS"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Pedido"
                            },
                            "examples": {
                                "Register": {
                                    "summary": "Cadastra um novo pedido",
                                    "value": {
                                        "delivery_date": "2022-10-05T12:09:04.374Z",
                                        "client_name": "João",
                                        "items_list_id": ["11", "12", "13"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Pedido cadastrado com sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Create": {
                                        "value": {
                                            "id": "4720c32a-9eee-4b63-8450-e175a536f924",
                                            "client_name": "João",
                                            "delivery_date": "2022-10-05T12:09:04.374Z",
                                            "items_list_id": [
                                                "1",
                                                "2",
                                                "3"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "É retornado quando um item da lista de ID's não é contrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "item list with id '38c9c1a2-7c82-4eed-9880-4609bfb0ed41z' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Retorna todos os COMPRAS cadastrados",
                "tags": ["COMPRAS"],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Search All": {
                                        "value": [
                                            {
                                                "id": "4720c32a-9eee-4b63-8450-e175a536f924",
                                                "client_name": "João",
                                                "delivery_date": "2022-10-05T12:09:04.374Z",
                                                "shopping_list": [
                                                    {
                                                        "product": "COLHER DESCARTÁVEL MASTER PRAFESTA BRANCA C/ 50UN",
                                                        "quantity": 3,
                                                        "price": 5.99
                                                    },
                                                    {
                                                        "product": "GARFO DESCARTÁVEL MASTER PRAFESTA CRYSTAL C/ 50UN",
                                                        "quantity": 2,
                                                        "price": 7.49
                                                    },
                                                    {
                                                        "product": "FACA DESCARTÁVEL MASTER PRAFESTA CRYSTAL C/ 50UN",
                                                        "quantity": 5,
                                                        "price": 8.99
                                                    }
                                                ],
                                                "total_amount": 77.9
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "summary": "Retorna um pedido específico de acordo com o ID informado",
                "tags": ["COMPRAS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Register": {
                                        "summary": "Retorna um pedido específico",
                                        "value": {
                                            "id": "4720c32a-9eee-4b63-8450-e175a536f924",
                                            "client_name": "João",
                                            "delivery_date": "2022-10-05T12:09:04.374Z",
                                            "items_list_id": [
                                                "1",
                                                "2",
                                                "3"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "É retornado quando um pedido não é encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "order with id '4720c32a-9skfjq23' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Altera um pedido de acordo com o ID informado",
                "tags": ["COMPRAS"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Pedido"
                            },
                            "examples": {
                                "Register": {
                                    "summary": "Altera um pedido",
                                    "value": {
                                        "client_name": "João",
                                        "delivery_date": "2022-10-05T12:09:04.374Z",
                                        "items_list_id": [
                                            "1",
                                            "2",
                                            "3"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Register": {
                                        "summary": "Mostra o pedido após alteração",
                                        "value": {
                                            "id": "4720c32a-9eee-4b63-8450-e175a536f924",
                                            "client_name": "João",
                                            "delivery_date": "2022-10-05T12:09:04.374Z",
                                            "items_list_id": [
                                                "1",
                                                "3"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "É retornado quando um produto não é encontrado",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Error": {
                                        "summary": "Error",
                                        "value": {
                                            "statusCode": 404,
                                            "message": "product with id '101' not found",
                                            "error": "Not Found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Usuário": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Nome do usuário"
                    },
                    "email": {
                        "type": "string",
                        "description": "Email do usuário"
                    },
                    "password": {
                        "type": "string",
                        "description": "Senha do usuário"
                    }
                }
            },
            "Produto": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Nome do Produto"
                    },
                    "price": {
                        "type": "float",
                        "description": "Preço do Produto"
                    },
                    "image_url": {
                        "type": "string",
                        "description": "Url da Imagem do Produto"
                    }
                }
            },
            "Compra": {
                "type": "object",
                "properties": {
                    "user_id": {
                        "type": "string",
                        "description": "ID do Usuário"
                    },
                    "product_id": {
                        "type": "string",
                        "description": "ID do Produto"
                    },
                    "quantity": {
                        "type": "int",
                        "description": "Quantidade do Produto"
                    },
                    "total_price": {
                        "type": "float",
                        "description": "Preço Total do Produto"
                    }
                }
            },
            "UserUpdate": {
                "type": "object",
                "properties": {
                    "password": {
                        "type": "string",
                        "description": "Nova Senha do Usuário"
                    }
                }
            }
        }
    }
}
